In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", 30)

In [2]:
trn = pd.read_csv('A:/shared/P428/Datasets/train_data.csv')
tst = pd.read_csv('A:/shared/P428/Datasets/test_data.csv')
df = pd.concat([trn, tst]).dropna().drop(['ID', 'Unnamed: 0'], axis=1)

In [4]:
trn.dropna().drop('Unnamed: 0', axis=1).to_csv('A:/shared/P428/Datasets/train_data_clean.csv', index=False)
tst.dropna().drop('Unnamed: 0', axis=1).to_csv('A:/shared/P428/Datasets/test_data_clean.csv', index=False)

In [17]:
df_cat = ['Gender', 'RaceEthnicity', 'LivingSituation', 'Education', 'BMI',
          'CurrSmoking', 'AlcUse', 'Diabetes', 'Hypertension', 'Dyslipidemia',
          'Frailty', 'FamHistHA', 'HistCancer', 'RegAspirin', 'Endpoint',
          'LipidLoweringAgents', 'AntihypertensiveAgents']
df_num = [col for col in df.columns if col not in df_cat]
df_num.remove('Treatment')

In [18]:
df.shape

(2291, 30)

In [22]:
display(df.mean())
display(df.std())
df['Gender'].value_counts()

C:\Users\EXT-ED~1\AppData\Local\Temp\21/ipykernel_3604/514677377.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  display(df.mean())

Age                        73.864653
Gender                      1.665648
LivingSituation             1.629419
Education                   4.191619
SBP                       135.109996
DBP                        77.402444
AbdCirc                    97.592318
AvgDominantGrpStr          25.220137
AvgGaitSpd                  3.802095
CurrSmoking                 2.464863
AlcUse                      1.649062
Diabetes                    0.164993
Hypertension                0.694020
Dyslipidemia                0.476211
Frailty                     0.655609
FamHistHA                   0.374072
HistCancer                  0.171541
HDL_mmolL                   1.570930
LDL_mmolL                   2.909079
eGFR_CKD                   74.806886
Hgb                        13.732431
RegAspirin                  0.367089
X3MS_Overall               93.525535
CESD_Overall                3.404627
Treatment                   1.504147
Endpoint                    0.105194
LipidLoweringAgents         0.557399
AntihypertensiveAgents      0.645133
dtype: float64

C:\Users\EXT-ED~1\AppData\Local\Temp\21/ipykernel_3604/514677377.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  display(df.std())

Age                        5.479818
Gender                     0.471866
LivingSituation            0.504295
Education                  1.371080
SBP                       17.134228
DBP                       10.093557
AbdCirc                   14.153390
AvgDominantGrpStr         11.656847
AvgGaitSpd                 1.699407
CurrSmoking                0.624787
AlcUse                     0.862070
Diabetes                   0.371256
Hypertension               0.460922
Dyslipidemia               0.499543
Frailty                    0.565869
FamHistHA                  0.483988
HistCancer                 0.388472
HDL_mmolL                  0.457630
LDL_mmolL                  0.851716
eGFR_CKD                  16.359387
Hgb                        1.288698
RegAspirin                 0.482116
X3MS_Overall               5.068494
CESD_Overall               3.410612
Treatment                  0.500092
Endpoint                   0.306871
LipidLoweringAgents        0.496803
AntihypertensiveAgents     0.478577
dtype: float64

2    1525
1     766
Name: Gender, dtype: int64

In [19]:
trt_grp = df.groupby('Treatment')
trt_grp.count()
for i, j in trt_grp:
    for col in df_cat:
        display(j[col].value_counts())

2    758
1    378
Name: Gender, dtype: int64

W    520
B    414
H    179
O     23
Name: RaceEthnicity, dtype: int64

2    708
1    418
3     10
Name: LivingSituation, dtype: int64

4    333
6    252
3    247
5    200
2     57
1     47
Name: Education, dtype: int64

over      453
obese     404
normal    273
under       6
Name: BMI, dtype: int64

3    608
2    457
1     71
Name: CurrSmoking, dtype: int64

1    695
3    291
2    150
Name: AlcUse, dtype: int64

0    958
1    178
Name: Diabetes, dtype: int64

1    798
0    338
Name: Hypertension, dtype: int64

0    598
1    538
Name: Dyslipidemia, dtype: int64

1    612
0    472
2     52
Name: Frailty, dtype: int64

0    693
1    443
Name: FamHistHA, dtype: int64

 0.0    929
 1.0    203
-1.0      4
Name: HistCancer, dtype: int64

0    713
1    423
Name: RegAspirin, dtype: int64

0    1027
1     109
Name: Endpoint, dtype: int64

1    624
0    512
Name: LipidLoweringAgents, dtype: int64

1    735
0    401
Name: AntihypertensiveAgents, dtype: int64

2    767
1    388
Name: Gender, dtype: int64

W    534
B    426
H    168
O     27
Name: RaceEthnicity, dtype: int64

2    686
1    455
3     14
Name: LivingSituation, dtype: int64

4    332
6    264
5    225
3    213
1     61
2     60
Name: Education, dtype: int64

over      471
obese     397
normal    284
under       3
Name: BMI, dtype: int64

3    619
2    445
1     91
Name: CurrSmoking, dtype: int64

1    699
3    299
2    157
Name: AlcUse, dtype: int64

0    955
1    200
Name: Diabetes, dtype: int64

1    792
0    363
Name: Hypertension, dtype: int64

0    602
1    553
Name: Dyslipidemia, dtype: int64

1    674
0    425
2     56
Name: Frailty, dtype: int64

0    741
1    414
Name: FamHistHA, dtype: int64

 0.0    949
 1.0    200
-1.0      6
Name: HistCancer, dtype: int64

0    737
1    418
Name: RegAspirin, dtype: int64

0    1023
1     132
Name: Endpoint, dtype: int64

1    653
0    502
Name: LipidLoweringAgents, dtype: int64

1    743
0    412
Name: AntihypertensiveAgents, dtype: int64

In [50]:
from scipy.stats import ttest_ind
for col in df_num:
    cols = []
    for i, j in trt_grp:
        cols.append(j[col])
    tval, pval = ttest_ind(a=cols[0], b=cols[1], alternative='two-sided', equal_var=False)
    print(col, pval)

Age 0.5195519608851598
SBP 0.49499240552712775
DBP 0.5843515166399628
AbdCirc 0.7207903075148461
AvgDominantGrpStr 0.7686015993107225
AvgGaitSpd 0.5236568643272574
HDL_mmolL 0.35283511580314764
LDL_mmolL 0.5435978874260738
eGFR_CKD 0.022623479147014392
Hgb 0.6097870811882576
X3MS_Overall 0.08947137606050076
CESD_Overall 0.04217866192551477

In [51]:
trt_grp.std()

,Age,Gender,LivingSituation,Education,SBP,DBP,AbdCirc,AvgDominantGrpStr,AvgGaitSpd,CurrSmoking,AlcUse,Diabetes,Hypertension,Dyslipidemia,Frailty,FamHistHA,HistCancer,HDL_mmolL,LDL_mmolL,eGFR_CKD,Hgb,RegAspirin,X3MS_Overall,CESD_Overall,Endpoint,LipidLoweringAgents,AntihypertensiveAgents
Treatment,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5.447792,0.471404,0.497983,1.350504,17.381945,10.090080,14.389333,11.456053,1.627518,0.612034,0.861473,0.363668,0.457375,0.499522,0.569967,0.487957,0.389442,0.453549,0.862644,16.197299,1.273871,0.483646,5.097328,3.205435,0.294653,0.497783,0.478111
2,5.512516,0.472519,0.510393,1.391472,16.891067,10.100038,13.922868,11.855554,1.767682,0.637252,0.863004,0.378550,0.464432,0.499766,0.560941,0.479750,0.387650,0.461636,0.841064,16.487791,1.303525,0.480760,5.035810,3.596658,0.318296,0.495923,0.479236

In [39]:
rf1 = pd.read_csv('A:/shared/P428/Ian_RF_Code/newTestRFProb.csv')
rf1['RiskQuartile1'] = pd.qcut(rf1['Prob'], q=4, labels=['q1', 'q2', 'q3', 'q4'])
rf2 = pd.read_csv('A:/shared/P428/RF_Weighted_Probs.csv')
display(rf1.head())
display(rf2.head())
data = pd.read_csv('A:/shared/P428/Datasets/test_data.csv').drop('Unnamed: 0', axis=1)

joined = rf1.merge(rf2, how='inner', left_on='ID', right_on='ID')
joint_q4 = joined[joined['RiskQuartile1'] == 'q4']
joint_q4 = joint_q4[joint_q4['RiskQuartile'] == 'q4']
intersect = joint_q4.shape[0]
union = 0
r1 = joined['RiskQuartile1']
r2 = joined['RiskQuartile']
for i in range(joined.shape[0]):
    if (r1[i] == 'q4') or (r2[i] == 'q4'):
        union += 1
print(intersect / union)

          ID  Prob RiskQuartile1
0  SAFE00013  0.45            q3
1  SAFE00032  0.16            q2
2  SAFE00044  0.18            q2
3  SAFE00072  0.17            q2
4  SAFE00115  0.71            q4

          ID  RiskScore RiskQuartile  Endpoint
0  SAFE00013   0.263294           q3         0
1  SAFE00032   0.125234           q2         0
2  SAFE00044   0.050240           q1         0
3  SAFE00072   0.131524           q2         0
4  SAFE00115   0.428412           q4         0

0.7308868501529052

In [23]:
intersectQ4 = joint_q4[['ID', 'RiskQuartile']].merge(data, how='inner', left_on='ID', right_on='ID')
intersectQ4.head()

,ID,RiskQuartile,Age,Gender,RaceEthnicity,LivingSituation,Education,BMI,SBP,DBP,...,LDL_mmolL,eGFR_CKD,Hgb,RegAspirin,X3MS_Overall,CESD_Overall,Treatment,Endpoint,LipidLoweringAgents,AntihypertensiveAgents
0,SAFE00115,q4,74.84,1,W,2,6,normal,119,69,...,2.4,82.829942,15.4,1,83,1,2,0,0,0
1,SAFE00142,q4,72.51,1,O,2,4,over,128,74,...,3.3,75.012057,13.1,1,79,0,1,0,1,1
2,SAFE00243,q4,76.81,2,B,2,4,obese,116,66,...,3.4,50.618709,12.1,0,88,7,2,0,1,1
3,SAFE00349,q4,74.48,2,W,2,4,over,151,87,...,4.0,84.908356,12.8,1,89,0,1,0,1,0
4,SAFE00353,q4,78.50,1,W,2,6,obese,131,80,...,2.2,80.691638,15.0,0,91,0,2,0,0,1

In [45]:
rf1 = pd.read_csv('A:/shared/P428/Ian_RF_Code/newTestRFProb.csv')
rf1['RiskQuartile'] = pd.qcut(rf1['Prob'], q=4, labels=['q1', 'q2', 'q3', 'q4'])
rf1 = rf1.merge(data, how='inner', left_on='ID', right_on='ID')
rf1.rename(columns={'LivingSituation': 'LivSit', 'AvgDominantGrpStr': 'DomGrpStr', 
                    'LipidLoweringAgents': 'LLA', 'AntihypertensiveAgents': 'AHA'}, inplace=True)
rf1.columns

Index(['ID', 'Prob', 'RiskQuartile', 'Age', 'Gender', 'RaceEthnicity',
       'LivSit', 'Education', 'BMI', 'SBP', 'DBP', 'AbdCirc', 'DomGrpStr',
       'AvgGaitSpd', 'CurrSmoking', 'AlcUse', 'Diabetes', 'Hypertension',
       'Dyslipidemia', 'Frailty', 'FamHistHA', 'HistCancer', 'HDL_mmolL',
       'LDL_mmolL', 'eGFR_CKD', 'Hgb', 'RegAspirin', 'X3MS_Overall',
       'CESD_Overall', 'Treatment', 'Endpoint', 'LLA', 'AHA'],
      dtype='object')

In [80]:
rf1_ohe = pd.get_dummies(rf1, columns=['RaceEthnicity', 'LivSit', 'Education', 'BMI', 'CurrSmoking', 'AlcUse', 'Frailty'])
rf1_ohe_q4 = rf1_ohe[rf1_ohe['RiskQuartile'] == 'q4']
display(rf1_ohe_q4.iloc[:, :27].groupby('Treatment').mean().round(3))
display(rf1_ohe_q4.iloc[:, 22:].groupby('Treatment').mean().round(3))
display(rf1_ohe_q4.iloc[:, 22:].groupby('Treatment').sum())

,Prob,Age,Gender,SBP,DBP,AbdCirc,DomGrpStr,AvgGaitSpd,Diabetes,Hypertension,Dyslipidemia,FamHistHA,HistCancer,HDL_mmolL,LDL_mmolL,eGFR_CKD,Hgb,RegAspirin,X3MS_Overall,CESD_Overall,Endpoint,LLA,AHA,RaceEthnicity_B
Treatment,,,,,,,,,,,,,,,,,,,,,,,,
1,0.616,77.436,1.662,138.431,78.092,92.877,22.467,4.207,0.169,0.731,0.423,0.400,0.262,1.575,2.800,68.884,13.666,0.369,88.000,3.215,0.169,0.523,0.669,0.392
2,0.601,76.731,1.561,138.682,77.736,97.385,25.912,4.405,0.209,0.797,0.520,0.318,0.189,1.553,2.768,68.956,13.795,0.365,88.655,3.595,0.264,0.608,0.703,0.432

,Endpoint,LLA,AHA,RaceEthnicity_B,RaceEthnicity_H,RaceEthnicity_O,RaceEthnicity_W,LivSit_1,LivSit_2,LivSit_3,Education_1,Education_2,Education_3,Education_4,Education_5,Education_6,BMI_normal,BMI_obese,BMI_over,BMI_under,CurrSmoking_1,CurrSmoking_2,CurrSmoking_3,AlcUse_1,AlcUse_2,AlcUse_3,Frailty_0,Frailty_1,Frailty_2
Treatment,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0.169,0.523,0.669,0.392,0.162,0.031,0.415,0.385,0.592,0.023,0.062,0.092,0.246,0.308,0.131,0.162,0.331,0.238,0.408,0.023,0.069,0.446,0.485,0.600,0.169,0.231,0.277,0.638,0.085
2,0.264,0.608,0.703,0.432,0.135,0.034,0.399,0.432,0.561,0.007,0.081,0.115,0.209,0.311,0.128,0.155,0.297,0.304,0.399,0.000,0.115,0.432,0.453,0.581,0.189,0.230,0.230,0.696,0.074

,Endpoint,LLA,AHA,RaceEthnicity_B,RaceEthnicity_H,RaceEthnicity_O,RaceEthnicity_W,LivSit_1,LivSit_2,LivSit_3,Education_1,Education_2,Education_3,Education_4,Education_5,Education_6,BMI_normal,BMI_obese,BMI_over,BMI_under,CurrSmoking_1,CurrSmoking_2,CurrSmoking_3,AlcUse_1,AlcUse_2,AlcUse_3,Frailty_0,Frailty_1,Frailty_2
Treatment,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,22,68,87,51,21,4,54,50,77,3,8,12,32,40,17,21,43,31,53,3,9,58,63,78,22,30,36,83,11
2,39,90,104,64,20,5,59,64,83,1,12,17,31,46,19,23,44,45,59,0,17,64,67,86,28,34,34,103,11

In [81]:
display(rf1_ohe.iloc[:, :27].groupby('RiskQuartile').mean().round(3))

,Prob,Age,Gender,SBP,DBP,AbdCirc,DomGrpStr,AvgGaitSpd,Diabetes,Hypertension,Dyslipidemia,FamHistHA,HistCancer,HDL_mmolL,LDL_mmolL,eGFR_CKD,Hgb,RegAspirin,X3MS_Overall,CESD_Overall,Treatment,Endpoint,LLA,AHA,RaceEthnicity_B
RiskQuartile,,,,,,,,,,,,,,,,,,,,,,,,,
q1,0.098,71.721,1.710,126.886,74.340,99.545,26.354,3.173,0.118,0.566,0.475,0.407,0.108,1.551,2.952,77.761,13.784,0.306,97.024,2.643,1.488,0.027,0.572,0.582,0.273
q2,0.210,73.266,1.719,135.795,78.640,96.799,25.403,3.687,0.140,0.662,0.468,0.417,0.183,1.608,2.978,75.519,13.805,0.378,96.450,3.522,1.536,0.065,0.543,0.579,0.281
q3,0.373,73.175,1.640,138.448,79.236,98.754,25.570,3.897,0.182,0.778,0.512,0.397,0.202,1.575,2.977,77.127,13.634,0.380,92.205,3.562,1.471,0.118,0.566,0.680,0.438
q4,0.608,77.060,1.608,138.565,77.903,95.277,24.301,4.313,0.191,0.766,0.475,0.356,0.223,1.563,2.783,68.922,13.735,0.367,88.349,3.417,1.532,0.219,0.568,0.687,0.414